// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250907104251_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("Domain.Novost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FajlPutanja")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GrupaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SlikaPutanja")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Novosti");
                });

            modelBuilder.Entity("Domain.Sekcija", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfesorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TerminOdrzavanja")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sekcije");
                });
#pragma warning restore 612, 618
        }
    }
}
